# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('ip_addr', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=22)),
                ('system_type', models.CharField(choices=[('linux', 'LINUX'), ('win32', 'WINDOWS')], max_length=32)),
                ('enaled', models.BooleanField(default=True)),
                ('online_date', models.DateField()),
                ('online_create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('dept', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('host_groups', models.ManyToManyField(blank=True, to='app03.HostGroup')),
                ('hosts', models.ManyToManyField(blank=True, to='app03.Host')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app03.User')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(to='app03.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.IDC'),
        ),
    ]
