# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head_img',
            field=models.ImageField(default=1111, upload_to='static/imgs/upload'),
            preserve_default=False,
        ),
    ]
