# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_article_head_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_commnet',
            new_name='parent_comment',
        ),
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='static/imgs/uploadCom'),
        ),
    ]
