# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_auto_20170306_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='app03.UserProfile'),
        ),
    ]
