# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_auto_20170224_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='speed',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
