# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app03', '0004_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.TextField(default='nothing....', max_length=1024)),
                ('member_limit', models.IntegerField(default=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to='app03.UserProfile')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.UserProfile')),
                ('members', models.ManyToManyField(related_name='group_members', to='app03.UserProfile')),
            ],
        ),
    ]
